apiVersion: {{ .Values.global.apiVersion }}
kind: {{ .Values.global.events.kinds.eventsource }}
metadata:
  name: {{ .Values.global.events.githubES.eventsource.name }}
  namespace: {{ .Values.global.namespaces.argoevents }}
spec:
  service:
    ports:
      - name: {{ .Values.global.events.githubES.eventsource.service.name }}
        port: 12000
        targetPort: 12000
  github:
    {{ .Values.global.events.githubES.eventsource.service.name }}:
      repositories:
        - owner: alejo-maya
          names:
            - hello-world-node
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://4.156.13.213.nip.io
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json