apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.global.events.githubES.apiToken.name }}
  namespace: {{ .Values.global.namespaces.argoevents }}
spec:
  encryptedData:
    token: AgA2Oa2inASZzBpsVh89VO/8370SWolMIfc7fP3joM88r1UpzjpAxwSDf4LsAdswbXritfHQqQRPkNVAHBO6KgVYqM2ezIhbWYDZzRx9tVwOuL7Z8+oCLFEKSTFgewpBHanwB0OPJoVq7ZlH4stlE/m7XmOPMoVQwnlL89tdJ4RgQeuFPchGOl0k7vfxKampyigZ3GCEdAZUCN9oI0e3Uqg47Gro4OPtarD10tv2M0EdZdy8WCS5q9j/F5KPTzn4Vn/a2oO/gowvELD096IhlP9phrRU0S6i5SzUf/TtBYfUefa+NPkL34LzHM1sFVwb5MOFHzlarMQRpVdLZx+xdXIbjDUSSa0Z0jykYt+Vs1zIvd3lNAH3kvy2KZyKDV/t2SokhRL+tXSKsYPDRrgTOxuIDpHkcKYL4JLfH+O7v5c37aZFdgPChvEKBHO7apUH+iPvSe4hvdDrd1/nXAAAWpRK3dp5CmVHj+x/fEAie/PmU76Ilx3MWv7aw/qTsHpnuT+UHusCGB0dJkfvAiUyvXUtxu4yQjqvmECLouEKD1i6UIeD0P2wjYOBp6paAVHcvXQ6PLlyp+ReBKSOHnjv5PMfqqG2/TuBZxemhQnvzX+5Anz1XsLJGFNygG2KOIICvc5CGmMEmoBtlPhUtdTHEqezrFnjCpJP1BrrzuZip6XYWcMyOSciC6dtawqtNxai52CemNYuX8lqIxyEVmpK2fxI5h+vOowg6zwhhNYz7KiSbkiPk6M/StTR
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.global.events.githubES.apiToken.name }}
      namespace: {{ .Values.global.namespaces.argoevents }}
    type: Opaque
