apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.events.kinds.sensor }}
metadata:
  name: github-sensor
  namespace: {{ .Values.namespacesargoevents }}
spec:
  template:
    serviceAccountName: {{ .Values.events.githubes.serviceAccount.name }}
  dependencies:
    - name: github-event
      eventSourceName: {{ .Values.events.githubeseventsource.name }}
      eventName: {{ .Values.events.githubeseventsource.service.name }}
  triggers:
    - template:
        name: trigger-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-workflow-
                namespace: {{ .Values.namespaces.workflows }}
              spec:
                workflowTemplateRef:
                  name: {{ .Values.workflows.templates.silly.name }}
