apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-resources
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: resources
    repoURL: 'https://github.com/alejo-maya/app-of-apps-2'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
