apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.events.github-es.serviceAccount.name }}
  namespace: {{ .Values.namespaces.argo-events }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-creator
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-creator-binding
  namespace: {{ .Values.namespaces.workflows }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.events.github-es.serviceAccount.name }}
    namespace: {{ .Values.namespaces.argo-events }}
roleRef:
  kind: ClusterRole
  name: argo-workflow-creator
  apiGroup: rbac.authorization.k8s.io
