apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/alejo-maya/argo-apps
    targetRevision: HEAD
  destination: 
    name: in-cluster
    server: https://kubernetes.default.svc

syncPolicy:
  automated:
    selfHeal: true
    prune: true


namespaces:
  argocd: argocd
  argo-events: argo-events
  argo: argo
