apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io


spec:
  destination:
    name: in-cluster
    namespace: argocd

    
  source:
    repoURL: 'https://github.com/alejo-maya/app-of-apps-2'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
