apiVersion: {{ .Values.global.apiVersion }}
kind: {{ .Values.global.kind }}
metadata:
  name: events
  finalizers: {{ .Values.global.metadata.finalizers }}
spec:
  destination:
    name: {{ .Values.global.spec.destination.name }}
    namespace: {{ .Values.global.namespaces.argocd }}
  source:
    path: helm/charts/stacks/events #events
    repoURL: {{ .Values.global.spec.source.repoURL }}
    targetRevision: {{ .Values.global.spec.source.targetRevision }}
    helm:
      valueFiles:
        - ../../../values.yaml
  project: {{ .Values.global.spec.project }}
  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: events
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     name: in-cluster
#     namespace: argocd
#   source:
#     path: helm/templates/stacks/events #events
#     repoURL: https://github.com/alejo-maya/app-of-apps-2
#     targetRevision: HEAD
#   project: default
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true