apiVersion: {{ .Values.global.apiVersion }}
kind: {{ .Values.global.kind }}
metadata:
  name: sealed-secrets
  namespace: {{ .Values.global.namespaces.argocd }}
spec:
  project: {{ .Values.global.spec.project }}
  destination:
    server: {{ .Values.global.spec.destination.server }}
    namespace: sealed-secrets
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.16.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}