apiVersion: {{ .Values.global.apiVersion }}
kind: {{ .Values.global.kind }}
metadata:
  name: sealed-secrets
  namespace: {{ .Values.global.namespaces.argocd }}
  finalizers: {{ .Values.global.metadata.finalizers }}
spec:
  project: {{ .Values.global.spec.project }}
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: v2.16.1
    helm:
      values.global: |
        fullnameOverride: sealed-secrets-controller
  destination: 
    namespace: kube-system
    server: {{ .Values.global.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
