apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.kind }}
metadata:
  name: argo-stack
  finalizers: {{ .Values.metadata.finalizers }}
spec:
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: {{ .Values.namespaces.argocd }}
  source:
    path: stacks/templates/argo-stack
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  project: {{ .Values.spec.project }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
