apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-deploy-image
  namespace: {{ .Values.global.namespaces.workflows }}
spec:
  entrypoint: full-deploy
  serviceAccountName: {{ .Values.global.workflows.serviceAccount.name }}
  volumes:
  - name: kaniko-secret
    secret:
      secretName: crcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: full-deploy
    dag:
      tasks:
      - name: get-latest-tag
        templateRef:
          name: get-update-tag
          template: get-and-update-tag
        arguments:
          parameters:
            - name: container_image
              value: alejomayasw/hello-world-node-test

      - name: build-push-container-image
        dependencies: [get-latest-tag]
        templateRef:
          name: build-push-image
          template: build-kaniko-git
          clusterScope: true
        arguments:
          parameters:
          - name: app_repo
            value: git://github.com/alejo-maya/hello-world-node
          - name: container_image
            value: alejomayasw/hello-world-node-test
          - name: container_tag
            value: "{{`{{`}}tasks.get-latest-tag.outputs.parameters.new_tag{{`}}`}}"