apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.workflows.serviceAccount.name }}
  namespace: {{ .Values.global.namespaces.workflows }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  namespace: {{ .Values.global.namespaces.workflows }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-role-binding
  namespace: {{ .Values.global.namespaces.workflows }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.workflows.serviceAccount.name }}
  namespace: {{ .Values.global.namespaces.workflows }}
