apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.kind }}
metadata:
  name: argo-events
  namespace: {{ .Values.namespaces.argocd }}
  finalizers: {{ .Values.metadata.finalizers }}
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: helm/templates/apps/argo-stack/argo-events
  destination: 
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.namespacesargoevents }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
