apiVersion: {{ .Values.global.apiVersion }}
kind: {{ .Values.global.kind }}
metadata:
  name: argo
  namespace: {{ .Values.global.namespaces.argocd }}
  finalizers: {{ .Values.global.metadata.finalizers }}
spec:
  project: {{ .Values.global.spec.project }}
  source:
    repoURL: {{ .Values.global.spec.source.repoURL }}
    targetRevision: {{ .Values.global.spec.source.targetRevision }}
    chart: helm/charts/apps/argo-stack/argo-workflows
  destination: 
    server: {{ .Values.global.spec.destination.server }}
    namespace: {{ .Values.global.namespaces.argo }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
