apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.kind }}
metadata:
  name: sealed-secrets
  namespace: {{ .Values.namespaces.argocd }}
  finalizers: {{ .Values.metadata.finalizers }}
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: v2.16.1
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
  destination: 
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
