apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alejo-maya/argo-apps.git
    targetRevision: HEAD
    path: events
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
